import fs from 'node:fs'
import path from 'node:path'
import { fontOverrides, portCss } from '../src/pages-home/port-css'
import type { SiteKey } from '../src/sites/config'

const DESIGN = path.resolve(import.meta.dirname, '../../design')
const OUT = path.resolve(import.meta.dirname, '../src/pages-home')
const file = (p: string) => fs.readFileSync(path.join(DESIGN, p), 'utf8')
const inlineStyle = (page: string) => {
  const m = /<style>([\s\S]*?)<\/style>/.exec(file(page))
  if (!m) throw new Error(`no <style> in ${page}`)
  return m[1]
}

// Same cascade order as each prototype's <head>.
const SOURCES: Record<Exclude<SiteKey, 'multimedia'>, () => string[]> = {
  logistics: () => [file('shared/genix.css'), file('shared/style-logistics.css')],
  homeupgrades: () => [file('shared/genix.css'), file('shared/style-homeupgrades.css'), inlineStyle('homeupgrades-home.html')],
  hub: () => [inlineStyle('hub-home.html')],
}

for (const [site, sources] of Object.entries(SOURCES) as [Exclude<SiteKey, 'multimedia'>, () => string[]][]) {
  const header = `/* GENERATED by web/scripts/port-css.ts from design/ — do not edit. Change the prototype, then run \`npm run port:css\`. */\n`
  const css = header + sources().map((s) => portCss(s, site)).join('\n') + '\n' + fontOverrides(site) + '\n'
  const target = path.join(OUT, site, `${site}.generated.css`)
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, css)
  console.log(`wrote ${path.relative(process.cwd(), target)} (${css.length} bytes)`)
}
